### ISSUE TITLE
Template won´t load

### ISSUE THREAD

**Issue by gelt00** [tailwindtoolbox/Admin-Template#1]
I have this odd issue, 

[https://imgur.com/hIBHtnM](url)

nothing of the tailwind css is loaded on a fresh download "admin,zip" from this web

**Comment by gelt00** [comment]
Not an issue, incompability with v1+

**Comment by tailwindtoolbox** [comment]
Hi @gelt00 
I've updated the template to v1 now, so please check it out now. 👍
