### ISSUE TITLE
Can't edit the content in the middle, I get half a screen width

### ISSUE THREAD

**Issue by idrisfab** [tailwindtoolbox/Admin-Template#6]
Hi, I'm very new to Tailwind, I'm trying to use this layout and find it very difficult to utilise the main area in the center of the page. 
Have you got an example or help on using the middle to store like, text or a large table? 
![image](https://user-images.githubusercontent.com/11630136/157145760-faaf073c-788f-4569-979b-0ef829178a02.png)
I'm trying to remove the content in the middle and have a basic area for different content. It just seems very difficult, I've tried vanilla CSS but nothing it working. Any clues?

**Comment by tailwindtoolbox** [comment]
Hi @idrisfab - I think this is what you are after? (just rename to .html)
[admin.txt](https://github.com/tailwindtoolbox/Admin-Template/files/8204468/admin.txt)

**Comment by idrisfab** [comment]
Yes! Thank you! I've been on this now for a few days. 
Bless!

**Comment by tailwindtoolbox** [comment]
Awesome. Feel free to ask me any questions if you get stuck on twitter (@amritnagi) 👍
